### PR TITLE
Release autoPaw 0.1.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
PRs contained in this release:

https://github.com/Workiva/autoPaw/pull/6

Diff Between Last Tag and Proposed Release: N/A
## How To +10/QA

``` bash
# skip the following steps if you've already initialized the project
git clone git@github.com:Workiva/autoPaw.git
cd autoPaw

# do not skip these!
git fetch && git checkout Release_0.1.0
Run unit tests
```

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1
- [x] Dev +1's only needed for Release ticket

@Workiva/release-management-p Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
